### ISSUE TITLE
Cant see wear apk in watch playstore with the release version of mobile app

### ISSUE THREAD

**Issue by pulkeet** [bitrise-io/sample-apps-wear-os#2]
created a release version of the mobile app [which has an embedded wear apk]
on the successful installation of the mobile app, the wear app should appear on the Wear PlayStore .but it's not showing.
I can see the wear app on Wear OS by Google on 2.24 but not 2.27
FYI: I even analyzed the Mobile Apk and I can the micro_wear apk embedded in it.

Any help will be appreciated.
Thank you in advance

**Comment by Roland-Bak** [comment]
Hi @pulkeet 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂
